# Generated by Django 5.1.7 on 2025-12-25 05:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_alter_comment_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_data",
            name="cover_photo",
            field=models.ImageField(blank=True, null=True, upload_to="cover_photos/"),
        ),
        migrations.AddField(
            model_name="user_data",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user_data",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="user_data",
            name="dob",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user_data",
            name="education",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="user_data",
            name="first_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="user_data",
            name="gender",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="user_data",
            name="location",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="user_data",
            name="mobile_number",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name="user_data",
            name="surname",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="user_data",
            name="work",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
