# Generated by Django 5.1.7 on 2025-12-25 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0009_user_data_cover_photo_user_data_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_data",
            name="bio",
            field=models.TextField(default="This is a default bio."),
        ),
        migrations.AlterField(
            model_name="user_data",
            name="education",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="user_data",
            name="first_name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="user_data",
            name="gender",
            field=models.CharField(default="unknown", max_length=10),
        ),
        migrations.AlterField(
            model_name="user_data",
            name="location",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="user_data",
            name="mobile_number",
            field=models.CharField(default="0000000000", max_length=15),
        ),
        migrations.AlterField(
            model_name="user_data",
            name="surname",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="user_data",
            name="work",
            field=models.CharField(default="", max_length=255),
        ),
    ]
