# Generated by Django 5.1.7 on 2025-12-25 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0010_alter_user_data_bio_alter_user_data_education_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user_data",
            name="dob",
        ),
        migrations.RemoveField(
            model_name="user_data",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="user_data",
            name="mobile_number",
        ),
        migrations.AlterField(
            model_name="user_data",
            name="bio",
            field=models.TextField(default=""),
        ),
    ]
